// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/assets/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/assets/[id].get').default>>>>
    }
    '/api/assets/categories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/assets/categories.get').default>>>>
    }
    '/api/assets': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/assets/index.get').default>>>>
    }
    '/api/companies': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/companies.get').default>>>>
    }
    '/api/procurement/purchase-orders': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/procurement/purchase-orders.get').default>>>>
    }
    '/api/procurement/purchase-orders/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/procurement/purchase-orders/[id].get').default>>>>
    }
    '/api/procurement/requisitions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/procurement/requisitions.get').default>>>>
    }
    '/api/procurement/requisitions/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/procurement/requisitions/[id].get').default>>>>
    }
    '/api/procurement/vendors': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/procurement/vendors.get').default>>>>
    }
    '/api/properties': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/properties.get').default>>>>
    }
    '/api/properties/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/properties/[id].get').default>>>>
    }
    '/api/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}