# Generated by Django 5.2.5 on 2026-02-09 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_number', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('lease', 'Lease'), ('license', 'License'), ('coworking_membership', 'Co-working Membership')], default='lease', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rent_amount', models.DecimalField(decimal_places=2, help_text='Monthly rent in INR', max_digits=12)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0, help_text='Security deposit in INR', max_digits=12)),
                ('rent_escalation_percent', models.DecimalField(decimal_places=2, default=0, help_text='Annual rent escalation %', max_digits=5)),
                ('notice_period_days', models.IntegerField(default=30, help_text='Notice period in days')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='draft', max_length=20)),
                ('document_url', models.URLField(blank=True, help_text='URL to lease agreement document')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='companies.company')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='spaces.space')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
