# Generated by Django 5.2.5 on 2026-02-09 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('private_office', 'Private Office'), ('open_desk', 'Open Desk'), ('meeting_room', 'Meeting Room'), ('virtual_office', 'Virtual Office'), ('hot_desk', 'Hot Desk')], default='private_office', max_length=20)),
                ('floor', models.IntegerField()),
                ('area', models.DecimalField(decimal_places=2, help_text='Area in sqft', max_digits=10)),
                ('capacity', models.IntegerField(blank=True, help_text='Number of people', null=True)),
                ('base_rent', models.DecimalField(decimal_places=2, help_text='Monthly base rent in INR', max_digits=12)),
                ('price_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amenities', models.JSONField(blank=True, default=list, help_text='List of amenities like WiFi, AC, etc.')),
                ('current_status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance'), ('reserved', 'Reserved')], default='available', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='properties.property')),
            ],
            options={
                'ordering': ['property', 'floor', 'code'],
                'unique_together': {('property', 'code')},
            },
        ),
    ]
