export default defineEventHandler((event) => {
    return {
        data: [
            {
                id: 1,
                assetNumber: "AST-2024-001",
                name: 'MacBook Pro 14"',
                description: "M3 Pro, 16GB RAM, 512GB SSD",
                category: { id: 1, name: "IT Equipment", code: "IT" },
                subcategory: "Laptop",
                make: "Apple",
                model: "MacBook Pro 14",
                serialNumber: "C02XG1JZJHD3",
                status: "in_use",
                condition: "excellent",
                propertyId: 1,
                property: { id: 1, name: "Cyber Towers" },
                location: "Floor 3, Desk 42",
                assignedTo: {
                    id: 2,
                    firstName: "Jane",
                    lastName: "Smith",
                    email: "jane@example.com",
                    department: "Engineering",
                },
                purchaseDate: "2024-01-15",
                warrantyExpiry: "2027-01-15",
                purchasePrice: 145000,
                currentValue: 130000,
                depreciationMethod: "straight_line",
                usefulLife: 5,
                poId: 2,
                vendorId: 2,
                vendor: { name: "TechWorld Electronics" },
                createdAt: "2024-01-20T10:00:00Z",
            },
            {
                id: 2,
                assetNumber: "AST-2024-002",
                name: "Ergonomic Executive Chair",
                description: "High-back mesh chair with lumbar support",
                category: { id: 2, name: "Furniture", code: "FUR" },
                subcategory: "Seating",
                make: "Herman Miller",
                model: "Aeron",
                serialNumber: "HM-AER-45621",
                status: "in_use",
                condition: "good",
                propertyId: 1,
                property: { id: 1, name: "Cyber Towers" },
                location: "Floor 5, Desk 12",
                assignedTo: {
                    id: 1,
                    firstName: "John",
                    lastName: "Doe",
                    email: "john@example.com",
                    department: "Facility",
                },
                purchaseDate: "2023-06-10",
                warrantyExpiry: "2025-06-10",
                purchasePrice: 85000,
                currentValue: 68000,
                depreciationMethod: "straight_line",
                usefulLife: 10,
                vendorId: 3,
                vendor: { name: "Office Comfort Furniture" },
                createdAt: "2023-06-15T10:00:00Z",
            },
            {
                id: 3,
                assetNumber: "AST-2024-003",
                name: "HP LaserJet Enterprise",
                description: "Color laser printer with network capability",
                category: { id: 1, name: "IT Equipment", code: "IT" },
                subcategory: "Printer",
                make: "HP",
                model: "LaserJet Enterprise M455dn",
                serialNumber: "VND4J02345",
                status: "in_use",
                condition: "good",
                propertyId: 2,
                property: { id: 2, name: "Tech Park Plaza" },
                location: "Floor 2, Print Room",
                purchaseDate: "2023-08-20",
                warrantyExpiry: "2024-08-20",
                purchasePrice: 45000,
                currentValue: 32000,
                depreciationMethod: "straight_line",
                usefulLife: 5,
                vendorId: 4,
                vendor: { name: "PrintMax Solutions" },
                createdAt: "2023-08-25T10:00:00Z",
            },
            {
                id: 4,
                assetNumber: "AST-2024-004",
                name: 'Samsung 27" Monitor',
                description: "4K UHD curved monitor",
                category: { id: 1, name: "IT Equipment", code: "IT" },
                subcategory: "Monitor",
                make: "Samsung",
                model: "UR59C",
                serialNumber: "SMNG789456123",
                status: "available",
                condition: "excellent",
                propertyId: 1,
                property: { id: 1, name: "Cyber Towers" },
                location: "IT Store Room",
                purchaseDate: "2024-02-01",
                warrantyExpiry: "2027-02-01",
                purchasePrice: 35000,
                currentValue: 35000,
                depreciationMethod: "straight_line",
                usefulLife: 5,
                createdAt: "2024-02-05T10:00:00Z",
            },
            {
                id: 5,
                assetNumber: "AST-2024-005",
                name: "Conference Table - 12 Seater",
                description:
                    "Solid wood conference table with cable management",
                category: { id: 2, name: "Furniture", code: "FUR" },
                subcategory: "Table",
                make: "Godrej",
                model: "Executive Series",
                serialNumber: "GDJ-CT-78521",
                status: "in_use",
                condition: "good",
                propertyId: 1,
                property: { id: 1, name: "Cyber Towers" },
                location: "Floor 4, Conference Room A",
                purchaseDate: "2022-03-15",
                purchasePrice: 120000,
                currentValue: 84000,
                depreciationMethod: "straight_line",
                usefulLife: 10,
                createdAt: "2022-03-20T10:00:00Z",
            },
            {
                id: 6,
                assetNumber: "AST-2024-006",
                name: "Air Conditioner - 2 Ton",
                description: "Inverter split AC",
                category: { id: 3, name: "HVAC", code: "HVAC" },
                subcategory: "Air Conditioner",
                make: "Daikin",
                model: "FTKL50TV16U",
                serialNumber: "DKN-AC-95632",
                status: "under_maintenance",
                condition: "fair",
                propertyId: 3,
                property: { id: 3, name: "Innovation Hub" },
                location: "Floor 2, Room 201",
                purchaseDate: "2021-05-10",
                purchasePrice: 65000,
                currentValue: 39000,
                depreciationMethod: "straight_line",
                usefulLife: 10,
                lastMaintenanceDate: "2024-01-15",
                nextMaintenanceDate: "2024-04-15",
                createdAt: "2021-05-15T10:00:00Z",
            },
            {
                id: 7,
                assetNumber: "AST-2024-007",
                name: "CCTV System - 16 Channel",
                description: "DVR with 16 HD cameras",
                category: { id: 4, name: "Security", code: "SEC" },
                subcategory: "Surveillance",
                make: "Hikvision",
                model: "DS-7216HQHI-K2",
                serialNumber: "HIK-DVR-14523",
                status: "in_use",
                condition: "good",
                propertyId: 1,
                property: { id: 1, name: "Cyber Towers" },
                location: "Security Room, Ground Floor",
                purchaseDate: "2022-11-20",
                warrantyExpiry: "2025-11-20",
                purchasePrice: 180000,
                currentValue: 126000,
                depreciationMethod: "straight_line",
                usefulLife: 7,
                createdAt: "2022-11-25T10:00:00Z",
            },
            {
                id: 8,
                assetNumber: "AST-2024-008",
                name: "Dell Latitude 5540",
                description: "i7, 16GB RAM, 512GB SSD",
                category: { id: 1, name: "IT Equipment", code: "IT" },
                subcategory: "Laptop",
                make: "Dell",
                model: "Latitude 5540",
                serialNumber: "DELL-LAT-78965",
                status: "disposed",
                condition: "poor",
                propertyId: 1,
                property: { id: 1, name: "Cyber Towers" },
                location: "-",
                purchaseDate: "2019-03-10",
                purchasePrice: 95000,
                currentValue: 0,
                depreciationMethod: "straight_line",
                usefulLife: 5,
                disposalDate: "2024-01-30",
                disposalReason: "End of life, hardware failure",
                disposalValue: 5000,
                createdAt: "2019-03-15T10:00:00Z",
            },
        ],
        pagination: {
            page: 1,
            limit: 20,
            total: 8,
            totalPages: 1,
        },
        stats: {
            total: 8,
            in_use: 5,
            available: 1,
            under_maintenance: 1,
            disposed: 1,
            totalValue: 514000,
            byCategory: [
                { name: "IT Equipment", count: 4 },
                { name: "Furniture", count: 2 },
                { name: "HVAC", count: 1 },
                { name: "Security", count: 1 },
            ],
        },
    };
});
