export default defineEventHandler((event) => {
    return {
        data: [
            {
                id: 1,
                poNumber: "PO-2024-001",
                prId: 3,
                pr: {
                    prNumber: "PR-2024-003",
                    title: "Cleaning Supplies Monthly",
                },
                vendorId: 1,
                vendor: {
                    id: 1,
                    name: "CleanPro Supplies",
                    contact: "Rajesh Kumar",
                    email: "sales@cleanpro.com",
                    phone: "+91-9876543210",
                },
                title: "Cleaning Supplies Order - Feb 2024",
                terms: "Net 30",
                deliveryDate: "2024-02-25",
                deliveryLocation: "Tech Park Plaza, Warehouse",
                subtotal: 32000,
                taxRate: 18,
                taxAmount: 5760,
                shippingCost: 500,
                discount: 1000,
                totalAmount: 37260,
                status: "sent",
                preparedBy: { id: 1, firstName: "John", lastName: "Doe" },
                approvedBy: { id: 2, firstName: "Jane", lastName: "Smith" },
                approvedAt: "2024-02-08T10:00:00Z",
                sentAt: "2024-02-08T14:00:00Z",
                items: [
                    {
                        id: 1,
                        itemName: "Floor Cleaner",
                        quantity: 20,
                        unit: "ltr",
                        unitPrice: 450,
                        totalPrice: 9000,
                        receivedQuantity: 0,
                    },
                    {
                        id: 2,
                        itemName: "Hand Sanitizer",
                        quantity: 50,
                        unit: "ltr",
                        unitPrice: 280,
                        totalPrice: 14000,
                        receivedQuantity: 0,
                    },
                    {
                        id: 3,
                        itemName: "Paper Towels",
                        quantity: 100,
                        unit: "box",
                        unitPrice: 90,
                        totalPrice: 9000,
                        receivedQuantity: 0,
                    },
                ],
                createdAt: "2024-02-07T09:00:00Z",
            },
            {
                id: 2,
                poNumber: "PO-2024-002",
                prId: 2,
                pr: { prNumber: "PR-2024-002", title: "IT Equipment Refresh" },
                vendorId: 2,
                vendor: {
                    id: 2,
                    name: "TechWorld Electronics",
                    contact: "Priya Sharma",
                    email: "orders@techworld.com",
                    phone: "+91-9876543211",
                },
                title: "MacBook Pro Order",
                terms: "Net 15, 50% Advance",
                deliveryDate: "2024-03-01",
                deliveryLocation: "Cyber Towers, IT Department",
                subtotal: 775000,
                taxRate: 18,
                taxAmount: 139500,
                shippingCost: 0,
                discount: 25000,
                totalAmount: 889500,
                status: "acknowledged",
                preparedBy: { id: 2, firstName: "Jane", lastName: "Smith" },
                approvedBy: { id: 1, firstName: "John", lastName: "Doe" },
                approvedAt: "2024-02-06T16:00:00Z",
                sentAt: "2024-02-06T17:00:00Z",
                items: [
                    {
                        id: 4,
                        itemName: 'MacBook Pro 14" M3 Pro',
                        quantity: 5,
                        unit: "pcs",
                        unitPrice: 145000,
                        totalPrice: 725000,
                        receivedQuantity: 0,
                    },
                    {
                        id: 5,
                        itemName: "USB-C Thunderbolt Dock",
                        quantity: 5,
                        unit: "pcs",
                        unitPrice: 10000,
                        totalPrice: 50000,
                        receivedQuantity: 0,
                    },
                ],
                createdAt: "2024-02-06T11:00:00Z",
            },
            {
                id: 3,
                poNumber: "PO-2024-003",
                vendorId: 3,
                vendor: {
                    id: 3,
                    name: "Office Comfort Furniture",
                    contact: "Amit Verma",
                    email: "sales@officecomfort.in",
                    phone: "+91-9876543212",
                },
                title: "Executive Chairs - Batch Order",
                terms: "Net 45",
                deliveryDate: "2024-02-15",
                deliveryLocation: "Cyber Towers, Floor 5",
                subtotal: 180000,
                taxRate: 18,
                taxAmount: 32400,
                shippingCost: 2500,
                discount: 5000,
                totalAmount: 209900,
                status: "partially_received",
                preparedBy: { id: 1, firstName: "John", lastName: "Doe" },
                items: [
                    {
                        id: 6,
                        itemName: "Executive Ergonomic Chair",
                        quantity: 20,
                        unit: "pcs",
                        unitPrice: 9000,
                        totalPrice: 180000,
                        receivedQuantity: 12,
                    },
                ],
                createdAt: "2024-01-20T10:00:00Z",
            },
            {
                id: 4,
                poNumber: "PO-2024-004",
                vendorId: 4,
                vendor: {
                    id: 4,
                    name: "PrintMax Solutions",
                    contact: "Deepak Gupta",
                    email: "orders@printmax.com",
                    phone: "+91-9876543213",
                },
                title: "Printer Cartridges Q1",
                terms: "COD",
                deliveryDate: "2024-02-10",
                deliveryLocation: "Innovation Hub, Store Room",
                subtotal: 45000,
                taxRate: 18,
                taxAmount: 8100,
                shippingCost: 0,
                discount: 0,
                totalAmount: 53100,
                status: "received",
                preparedBy: { id: 3, firstName: "Mike", lastName: "Wilson" },
                receivedAt: "2024-02-10T11:00:00Z",
                items: [
                    {
                        id: 7,
                        itemName: "HP Toner 85A",
                        quantity: 30,
                        unit: "pcs",
                        unitPrice: 1500,
                        totalPrice: 45000,
                        receivedQuantity: 30,
                    },
                ],
                createdAt: "2024-02-01T14:00:00Z",
            },
        ],
        pagination: {
            page: 1,
            limit: 20,
            total: 4,
            totalPages: 1,
        },
        stats: {
            draft: 0,
            sent: 1,
            acknowledged: 1,
            partially_received: 1,
            received: 1,
            total: 4,
            totalValue: 1189760,
        },
    };
});
