export default defineEventHandler((event) => {
    return {
        data: [
            {
                id: 1,
                prNumber: "PR-2024-001",
                title: "Office Furniture Q1",
                description:
                    "Procurement of office chairs and desks for new hires",
                requestedBy: {
                    id: 1,
                    firstName: "John",
                    lastName: "Doe",
                    email: "john@example.com",
                },
                department: "Facility",
                propertyId: 1,
                property: { id: 1, name: "Cyber Towers" },
                priority: "high",
                category: "furniture",
                requiredDate: "2024-03-15",
                status: "pending_approval",
                totalEstimatedAmount: 250000,
                items: [
                    {
                        id: 1,
                        itemName: "Executive Chair",
                        quantity: 10,
                        unit: "pcs",
                        estimatedUnitPrice: 15000,
                        totalEstimatedPrice: 150000,
                    },
                    {
                        id: 2,
                        itemName: "Work Desk",
                        quantity: 10,
                        unit: "pcs",
                        estimatedUnitPrice: 10000,
                        totalEstimatedPrice: 100000,
                    },
                ],
                requestedAt: "2024-02-01T10:00:00Z",
                createdAt: "2024-02-01T10:00:00Z",
            },
            {
                id: 2,
                prNumber: "PR-2024-002",
                title: "IT Equipment Refresh",
                description:
                    "Replacement of aging laptops for development team",
                requestedBy: {
                    id: 2,
                    firstName: "Jane",
                    lastName: "Smith",
                    email: "jane@example.com",
                },
                department: "IT",
                propertyId: 1,
                property: { id: 1, name: "Cyber Towers" },
                priority: "urgent",
                category: "it_hardware",
                requiredDate: "2024-02-28",
                status: "approved",
                totalEstimatedAmount: 800000,
                items: [
                    {
                        id: 3,
                        itemName: 'MacBook Pro 14"',
                        quantity: 5,
                        unit: "pcs",
                        estimatedUnitPrice: 150000,
                        totalEstimatedPrice: 750000,
                    },
                    {
                        id: 4,
                        itemName: "USB-C Dock",
                        quantity: 5,
                        unit: "pcs",
                        estimatedUnitPrice: 10000,
                        totalEstimatedPrice: 50000,
                    },
                ],
                approverId: 1,
                approvedAt: "2024-02-05T14:30:00Z",
                requestedAt: "2024-02-03T09:00:00Z",
                createdAt: "2024-02-03T09:00:00Z",
            },
            {
                id: 3,
                prNumber: "PR-2024-003",
                title: "Cleaning Supplies Monthly",
                description: "Monthly cleaning and sanitation supplies",
                requestedBy: {
                    id: 3,
                    firstName: "Mike",
                    lastName: "Wilson",
                    email: "mike@example.com",
                },
                department: "Admin",
                propertyId: 2,
                property: { id: 2, name: "Tech Park Plaza" },
                priority: "medium",
                category: "office_supplies",
                requiredDate: "2024-02-20",
                status: "converted_to_po",
                totalEstimatedAmount: 35000,
                items: [
                    {
                        id: 5,
                        itemName: "Floor Cleaner",
                        quantity: 20,
                        unit: "ltr",
                        estimatedUnitPrice: 500,
                        totalEstimatedPrice: 10000,
                    },
                    {
                        id: 6,
                        itemName: "Hand Sanitizer",
                        quantity: 50,
                        unit: "ltr",
                        estimatedUnitPrice: 300,
                        totalEstimatedPrice: 15000,
                    },
                    {
                        id: 7,
                        itemName: "Paper Towels",
                        quantity: 100,
                        unit: "box",
                        estimatedUnitPrice: 100,
                        totalEstimatedPrice: 10000,
                    },
                ],
                convertedToPoId: 1,
                requestedAt: "2024-01-25T11:00:00Z",
                createdAt: "2024-01-25T11:00:00Z",
            },
            {
                id: 4,
                prNumber: "PR-2024-004",
                title: "HVAC Maintenance Parts",
                description: "Spare parts for quarterly HVAC maintenance",
                requestedBy: {
                    id: 4,
                    firstName: "Sarah",
                    lastName: "Johnson",
                    email: "sarah@example.com",
                },
                department: "Facility",
                propertyId: 3,
                property: { id: 3, name: "Innovation Hub" },
                priority: "low",
                category: "maintenance",
                requiredDate: "2024-04-01",
                status: "draft",
                totalEstimatedAmount: 120000,
                items: [
                    {
                        id: 8,
                        itemName: "AC Filter",
                        quantity: 50,
                        unit: "pcs",
                        estimatedUnitPrice: 1500,
                        totalEstimatedPrice: 75000,
                    },
                    {
                        id: 9,
                        itemName: "Compressor Oil",
                        quantity: 30,
                        unit: "ltr",
                        estimatedUnitPrice: 1500,
                        totalEstimatedPrice: 45000,
                    },
                ],
                requestedAt: "2024-02-06T08:00:00Z",
                createdAt: "2024-02-06T08:00:00Z",
            },
        ],
        pagination: {
            page: 1,
            limit: 20,
            total: 4,
            totalPages: 1,
        },
        stats: {
            draft: 1,
            pending_approval: 1,
            approved: 1,
            converted_to_po: 1,
            total: 4,
            totalValue: 1205000,
        },
    };
});
