export default defineEventHandler((event) => {
    return {
        data: [
            {
                id: 1,
                name: "CleanPro Supplies",
                code: "VND-001",
                type: "supplier",
                category: "cleaning_supplies",
                status: "active",
                contact: {
                    name: "Rajesh Kumar",
                    email: "sales@cleanpro.com",
                    phone: "+91-9876543210",
                    designation: "Sales Manager",
                },
                address: {
                    street: "45, Industrial Area Phase 2",
                    city: "Gurugram",
                    state: "Haryana",
                    pincode: "122001",
                    country: "India",
                },
                bankDetails: {
                    bankName: "HDFC Bank",
                    accountNumber: "XXXX1234",
                    ifsc: "HDFC0001234",
                },
                gstNumber: "06ABCDE1234F1Z5",
                panNumber: "ABCDE1234F",
                rating: 4.5,
                totalOrders: 24,
                totalValue: 850000,
                createdAt: "2023-01-15T10:00:00Z",
            },
            {
                id: 2,
                name: "TechWorld Electronics",
                code: "VND-002",
                type: "supplier",
                category: "it_hardware",
                status: "active",
                contact: {
                    name: "Priya Sharma",
                    email: "orders@techworld.com",
                    phone: "+91-9876543211",
                    designation: "Account Manager",
                },
                address: {
                    street: "B-12, Nehru Place",
                    city: "New Delhi",
                    state: "Delhi",
                    pincode: "110019",
                    country: "India",
                },
                gstNumber: "07FGHIJ5678K2L6",
                panNumber: "FGHIJ5678K",
                rating: 4.8,
                totalOrders: 12,
                totalValue: 2500000,
                createdAt: "2023-03-20T10:00:00Z",
            },
            {
                id: 3,
                name: "Office Comfort Furniture",
                code: "VND-003",
                type: "supplier",
                category: "furniture",
                status: "active",
                contact: {
                    name: "Amit Verma",
                    email: "sales@officecomfort.in",
                    phone: "+91-9876543212",
                    designation: "Director",
                },
                address: {
                    street: "Plot 78, Sector 18",
                    city: "Noida",
                    state: "Uttar Pradesh",
                    pincode: "201301",
                    country: "India",
                },
                gstNumber: "09KLMNO9012P3Q7",
                panNumber: "KLMNO9012P",
                rating: 4.2,
                totalOrders: 8,
                totalValue: 1200000,
                createdAt: "2023-06-10T10:00:00Z",
            },
            {
                id: 4,
                name: "PrintMax Solutions",
                code: "VND-004",
                type: "supplier",
                category: "office_supplies",
                status: "active",
                contact: {
                    name: "Deepak Gupta",
                    email: "orders@printmax.com",
                    phone: "+91-9876543213",
                    designation: "Sales Executive",
                },
                address: {
                    street: "23, MG Road",
                    city: "Bangalore",
                    state: "Karnataka",
                    pincode: "560001",
                    country: "India",
                },
                gstNumber: "29PQRST3456U4V8",
                panNumber: "PQRST3456U",
                rating: 4.0,
                totalOrders: 36,
                totalValue: 450000,
                createdAt: "2022-11-05T10:00:00Z",
            },
            {
                id: 5,
                name: "SecureGuard Services",
                code: "VND-005",
                type: "service_provider",
                category: "security",
                status: "active",
                contact: {
                    name: "Vikram Singh",
                    email: "contracts@secureguard.in",
                    phone: "+91-9876543214",
                    designation: "Operations Head",
                },
                address: {
                    street: "Tower A, Cyber City",
                    city: "Gurugram",
                    state: "Haryana",
                    pincode: "122002",
                    country: "India",
                },
                gstNumber: "06UVWXY7890Z5A9",
                panNumber: "UVWXY7890Z",
                rating: 4.6,
                totalOrders: 5,
                totalValue: 3600000,
                contractType: "amc",
                contractExpiry: "2024-12-31",
                createdAt: "2022-08-15T10:00:00Z",
            },
        ],
        pagination: {
            page: 1,
            limit: 20,
            total: 5,
            totalPages: 1,
        },
        stats: {
            total: 5,
            active: 5,
            inactive: 0,
            suppliers: 4,
            serviceProviders: 1,
        },
    };
});
